### PR TITLE
[OKU-20] Unit tests - Authentication

### PR DESCRIPTION
**Pull request by enricodelarosa**
Should I include the coverage directory in the repo or can I just add it to .gitignore?

### CODE REVIEW

**Review by idiglove — COMMENTED** [review]
Yes let's remove the coverage files
Good job btw

**Comment by idiglove** [comment]
Can you also add the Test report on your description?

**Comment by enricodelarosa** [comment]
Is it alright if I add the test report on the description on the other merge request that also covers the unit test for reviews?

**Comment by enricodelarosa** [comment]
Screenshot of Test Result
image

**Review by idiglove — APPROVED** [review]
Great job 💯

**Pull request merged**
